MedKit
KevinCabrera25/ProyectoSemestral2-Desert pull request #2
Opened 2022-10-26 18:55 UTC by KevinCabrera25

Functional MedKits have been implemented in this version.

Whenever the Player enters in the OnTriggerEvent a CompareTag condition is used to analyse if the MedKit has been found, and if so the prop is destroyed after adding a 30 value to the Player's HP.

2022-10-26 19:03 UTC, Horothenic requested changes

2022-10-26 19:03 UTC, Horothenic commented on Assets/_Main/Scripts/PlayerHP.cs
> +            StartCoroutine(Grab(other.GetComponent<MeshRenderer>()));
You are painting the medkit?

2022-10-26 19:03 UTC, Horothenic commented on Assets/_Main/Scripts/PlayerHP.cs
>  using System.Collections.Generic;
Remove unused libraries

2022-10-26 19:03 UTC, Horothenic commented on Assets/_Main/Scripts/PlayerHP.cs
> +    [SerializeField] private TextMeshProUGUI _playerHPUI;
Initialize

2022-10-31 14:17 UTC, KevinCabrera25 commented on Assets/_Main/Scripts/PlayerHP.cs
>  using System.Collections.Generic;
Done

2022-10-31 14:17 UTC, KevinCabrera25 commented on Assets/_Main/Scripts/PlayerHP.cs
> +    [SerializeField] private TextMeshProUGUI _playerHPUI;
Done

2022-10-31 14:19 UTC, Horothenic approved these changes

2022-10-31 14:19 UTC, merged